CREATE TABLE LOCATION (_id INTEGER PRIMARY KEY, SIDO TEXT, GUGUN TEXT, DONG TEXT, X INTEGER, Y INTEGER);

INSERT INTO LOCATION(SIDO, GUGUN, DONG, X, Y) VALUES("서울특별시",,,60,127);
INSERT INTO LOCATION(SIDO, GUGUN, DONG, X, Y) VALUES("서울특별시","종로구",,60,127);
INSERT INTO LOCATION(SIDO, GUGUN, DONG, X, Y) VALUES("서울특별시","종로구","청운효자동",60,127);
INSERT INTO LOCATION(SIDO, GUGUN, DONG, X, Y) VALUES("서울특별시","종로구","사직동",60,127);
INSERT INTO LOCATION(SIDO, GUGUN, DONG, X, Y) VALUES("서울특별시","종로구","삼청동",60,127);
INSERT INTO LOCATION(SIDO, GUGUN, DONG, X, Y) VALUES("서울특별시","종로구","부암동",60,127);
INSERT INTO LOCATION(SIDO, GUGUN, DONG, X, Y) VALUES("서울특별시","종로구","평창동",60,127);
INSERT INTO LOCATION(SIDO, GUGUN, DONG, X, Y) VALUES("서울특별시","종로구","무악동",60,127);
INSERT INTO LOCATION(SIDO, GUGUN, DONG, X, Y) VALUES("서울특별시","종로구","교남동",60,127);
INSERT INTO LOCATION(SIDO, GUGUN, DONG, X, Y) VALUES("서울특별시","종로구","가회동",60,127);

SELECT * FROM LOCATION WHERE SIDO LIKE "%평창%" OR DONG LIKE "%동%";